-- Script para actualizar con los 76 semilleros activos oficiales del PIP
-- Primero limpiamos la tabla
TRUNCATE TABLE semilleros RESTART IDENTITY CASCADE;

-- Insertamos los 76 semilleros activos
INSERT INTO semilleros (name, description, faculty, area, contact_name, contact_email, image_url, status) VALUES
-- Economía
('Macro', 'El semillero macro nació en 2017 por la iniciativa de un grupo de estudiantes que querían reunirse a profundizar en temas de frontera en la investigación macroeconómica.', 'Economía', 'Investigación', 'David Perez-Reyna', 'd.perez-reyna@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('EconoMÍA y Género', 'Desde MÍA Uniandes creamos el Semillero de Investigación EconoMÍA y Género, el cual busca tener un espacio de discusión de artículos académicos de economía sobre temas de género.', 'Economía', 'Investigación', 'Daniela Vlasak', 'd.vlasak@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Investigación de Adam Smith', 'El semillero nació este semestre 2023-1 para estudiar la teoría moral y estética de Adam Smith y comprender sus vínculos con la teoría del valor.', 'Economía', 'Investigación', 'Jimena Hurtado', 'jihurtad@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Medicina
('Ciencias Básicas Médicas', 'Aplicaciones de la citometría de flujo, Neuroinmmunología y Respuesta inmune a enfermedades infecciosas.', 'Medicina', 'Investigación', 'John Mario González Escobar', 'johgonza@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Diabetes, lípidos y metabolismo UniAndes', 'Grupo de investigación enfocado en temáticas relacionadas con el metabolismo humano y sus alteraciones, desde las perspectivas básica, clínica y epidemiológica.', 'Medicina', 'Investigación', 'Carlos Olimpo Mendivil Anaya', 'cmendivi@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Grupo de epidemiología de la Universidad de los Andes (Epiandes)', 'Actividad física y nutrición, Economía de la Salud, Enfermedades crónicas y estilo de vida, Epidemiología Clínica.', 'Medicina', 'Investigación', 'Olga Lucía Sarmiento', 'osarmien@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Neurociencia Traslacional', 'Semillero interdisciplinario en medicina que integra la mirada de las ciencias básicas en la medicina humana aplicada a modelo animal pez cebra.', 'Medicina', 'Investigación', 'Natalia Mejía Gaviria', 'nmejia@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('REUMAVANCE', 'Grupo inter y transdisciplinar que busca responder a vacíos del conocimiento en el área de la autoinmunidad y enfermedades reumatológicas.', 'Medicina', 'Investigación', 'Gerardo Quintana López', 'g.quintana20@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Neurofisiología Celular', 'Trabajamos proyectos enfocados al estudio de los procesos neuroinflamatorios de las enfermedades neurodegenerativas.', 'Medicina', 'Investigación', 'Karina Vargas Sanchez', 'j.vargass@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Laboratorio de Ciencias Básicas Médicas (CBMU)', 'Investigación centrada en la respuesta inmune en enfermedades infecciosas y aplicaciones de la citometría de flujo.', 'Medicina', 'Investigación', 'John M. González', 'johgonza@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Investigación en Ortopedia y Traumatología', 'Fomenta la formación académica e investigativa de estudiantes y profesionales interesados en profundizar en esta especialidad médica.', 'Medicina', 'Investigación', 'Manuela Lorduy Ariza', 'm.lorduy@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Derecho
('Estudios Interdisciplinarios en Tributación (SEIT)', 'Semillero de investigación en Estudios Interdisciplinarios de la Tributación donde profesores, estudiantes y egresados producen investigaciones de calidad en tributación.', 'Derecho', 'Investigación', 'Eleonora Lozano', 'elozano@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Público Administrativo (SPA)', 'Espacio de encuentro para la discusión y reflexión de temas relacionados con el derecho administrativo.', 'Derecho', 'Investigación', 'Carolina Moreno', 'camoreno@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Resolución de Conflictos', 'Espacio diseñado para la creación de una comunidad académica dedicada a la reflexión crítica sobre el conflicto y los mecanismos de resolución de controversias.', 'Derecho', 'Investigación', 'Emilce Coy', 'cj.conciliacion@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Ingeniería
('Robocol', 'Iniciativa estudiantil enfocada en el desarrollo de proyectos de robótica para competencias internacionales.', 'Ingeniería', 'Investigación', 'Maria Camila Martinez', 'robocol@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de la línea de investigación de Ingeniería celular y Bioimpresión', 'Investigación en ingeniería celular y bioimpresión aplicada a la medicina.', 'Ingeniería', 'Investigación', 'Carolina Muñoz Camargo', 'c.munoz2016@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de investigación en Biomecánica - IBIOMECH', 'Espacio destinado al estudio del movimiento humano, enfocado en análisis de gestos deportivos y diseño de dispositivos ortopédicos.', 'Ingeniería', 'Investigación', 'Christian Javier Cifuentes De la Portilla', 'cc.cifuentes@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Ciencias Sociales
('Geografías del Poder', 'Trabajo con comunidades para promover el empoderamiento territorial, la organización y la capacidad de acción comunitaria.', 'Ciencias Sociales', 'Investigación', 'Luis Sánchez', 'ld.sanchez20@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Laboratorio Urbano. NextGenC Generacion Conectada', 'Investigación urbana enfocada en la generación conectada.', 'Ciencias Sociales', 'Investigación', 'Friederike Fleischer', 'f.fleischer406@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Narcolombia', 'Semillero de investigación y creación sobre narcotráfico y cultura en Colombia.', 'Ciencias Sociales', 'Investigación y creación', 'Xavier Andrade', 'sj.andrade@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Laboratorio de cognición', 'Espacio de formación e investigación en cognición y prácticas de aprendizaje con análisis de datos cuantitativos y lenguaje natural.', 'Ciencias Sociales', 'Investigación', 'William Jiménez', 'w.jimenezleal@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de investigación en neurociencia social', 'Estudio empírico de los mecanismos neurales subyacentes a los procesos de la cognición social.', 'Ciencias Sociales', 'Investigación', 'Sandra Jimena Báez Buitrago', 'sj.baez@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Psicogerontología', 'Fomenta el desarrollo de habilidades en investigación para el estudio del envejecimiento y la vejez desde un enfoque de curso de vida.', 'Ciencias Sociales', 'Investigación', 'Maria Fernanda Reyes', 'm.reyes8@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('EcoBites', 'Discusión de conceptos de la teoría ecológica de la percepción y sus aplicaciones a filosofía de la lógica, de la mente y de la acción.', 'Ciencias Sociales', 'Investigación', 'Tomás Barrero Guzmán', 'ta.barrero32@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- ArquiDis
('Movilidad sostenible y territorio', 'Investigación sobre movilidad sostenible y ordenamiento territorial.', 'ArquiDis', 'Investigación', 'C. Erik Vergel-Tovar', 'c.vergel@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Cuerpo y movimiento expandido', 'Estudio del papel inaugural que juega el movimiento del cuerpo en la conformación del espacio y la experiencia del tiempo.', 'ArquiDis', 'Investigación y creación', 'Lucas Ariza Parada', 'l.ariza48@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Diseño inspirado en Emociones', 'Consolidar un espacio para compartir, discutir, construir y desarrollar proyectos relacionados al Diseño Inspirado en las Emociones.', 'ArquiDis', 'Investigación y creación', 'Angie Henríquez Martínez', 'a.henriquez1291@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Observatorio de Arquitectura en Colombia', 'Observatorio enfocado en el análisis de la arquitectura contemporánea en Colombia.', 'ArquiDis', 'Investigación y creación', 'Ingrid Quintana Guerrero', 'i.quintana20@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Artes y Humanidades
('Lo leve y lo curatorial', 'Pequeña comunidad flotante de personas interesadas en indagar por lo curatorial y sus dispositivos más allá del formato expositivo.', 'Artes y Humanidades', 'Creación', 'Carolina Cerón', 'c.ceron50@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Escritura experimental', 'Semillero enfocado en explorar formas experimentales de escritura creativa.', 'Artes y Humanidades', 'Creación', 'Carolina Cerón', 'c.ceron50@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero VVV', 'Espacio informal para el desarrollo y apoyo de proyectos creativos que usen herramientas electrónicas y de programación.', 'Artes y Humanidades', 'Creación', 'David Peña', 'd.penal@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Estudios de Japón', 'Contribuir a la consolidación de los estudios de Japón en la Universidad y el país, analizando cultura visual con perspectiva de género.', 'Artes y Humanidades', 'Investigación', 'Betsy Forero Montoya', 'b.forero@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de fotografía', 'Espacio interdisciplinar donde se analiza y piensa el medio fotográfico desde diferentes perspectivas teóricas, históricas y prácticas.', 'Artes y Humanidades', 'Investigación', 'Juanita Solano', 'juani-so@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero la Imagen Colonial', 'Análisis de cómo se produjeron, usaron y se pensaron las imágenes durante la Colonia en la Nueva Granada.', 'Artes y Humanidades', 'Investigación', 'Olga Acosta', 'oi.acosta@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero Laboratorio de Arte y Arqueología Andina (L3A)', 'Espacio de investigación y creación interdisciplinar que reúne estudiantes interesados en el arte y la arqueología del área andina.', 'Artes y Humanidades', 'Investigación', 'Alexander Herrera', 'alherrer@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero Historia y Humanidades Digitales', 'Desarrollar habilidades para pensar la historia desde problemas conceptuales y metodológicos vinculados a las humanidades digitales.', 'Artes y Humanidades', 'Investigación', 'Maria José Afanador', 'mj.afanador@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Es de Lope', 'Semillero dedicado al estudio de la obra dramática de Lope de Vega, con especial énfasis en la edición crítica.', 'Artes y Humanidades', 'Investigación', 'Santiago Restrepo', 'srestreporamirez@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Humanidades Digitales (HD)- Biblioteca Digital Soledad Acosta', 'Repositorio digital para acceder a la obra de la escritora Soledad Acosta de Samper con herramientas de humanidades digitales.', 'Artes y Humanidades', 'Investigación y creación', 'Carolina Alzate', 'calzate@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Literatura hispánica y tradiciones discursivas', 'Estudio de corpus textuales donde se evidencia la presencia de moldes normativos convencionalizados en la literatura hispánica.', 'Artes y Humanidades', 'Investigación', 'Hugo Hernán Ramírez', 'huramire@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('María Mercedes Carranza', 'Edición y estudio del archivo de María Mercedes Carranza, promoviendo la publicación de artículos sobre edición de textos.', 'Artes y Humanidades', 'Investigación', 'Jerónimo Pizarro', 'j.pizarro188@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Patrimonio bibliográfico neogranadino', 'Estudio de libros antiguos, historia de la imprenta en Nueva Granada, circulación de libros y el saber.', 'Artes y Humanidades', 'Investigación', 'Andrea Lozano-Vásquez', 'a.lozano72@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Rafael Humberto Moreno-Durán', 'Edición y estudio del archivo de Rafael Humberto Moreno-Durán con reflexión teórica sobre edición de textos.', 'Artes y Humanidades', 'Investigación', 'Jerónimo Pizarro', 'j.pizarro188@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('LA COOLTURE: investigación y creación sobre la sociedad del entretenimiento', 'Pensar críticamente la sociedad desde la perspectiva del entretenimiento donde el criterio de verdad es lo cool & pop.', 'Artes y Humanidades', 'Creación', 'Omar Rincon', 'orincon@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Cuerpos que hablan', 'Semillero de exploración y ejercicios de laboratorio para crear con y desde el cuerpo de manera expresiva con intención estética.', 'Artes y Humanidades', 'Investigación y creación', 'Sandra Beatriz Sanchez Lopez', 'ssanchez@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('BLAST', 'Promover la difusión de los nuevos repertorios creados en el área de composición musical, visibilizando el trabajo de estudiantes.', 'Artes y Humanidades', 'Investigación', 'Laura Sophía Bacca', 'ls.bacca@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semilleros LEAP', 'Semillero del Laboratorio de Experimentación en Arte y Política.', 'Artes y Humanidades', 'Investigación', 'Mario Omar Fernández', 'mo.fernandez@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero Hoja González', 'Vida y práctica de archivo a partir de la edición semana a semana del semestre académico de la publicación González.', 'Artes y Humanidades', 'Creación', 'Lucas Ospina', 'luospina@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero Amanecer la Palabra', 'Trabaja en conjunto con Tramas Textiles del Departamento de Diseño.', 'Artes y Humanidades', 'Creación', 'María Margarita Jiménez', 'marjimen@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de animación: Casa carrusel', 'Espacio de creación y experimentación en animación.', 'Artes y Humanidades', 'Creación', 'Fredy Buitrago', 'f.buitragot@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de fotografía: Revista Atemporal', 'Proyecto editorial fotográfico con enfoque artístico.', 'Artes y Humanidades', 'Creación', 'Santiago Forero Ramirez', 's.foreror@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero Escena Expandida', 'Exploración de las artes escénicas expandidas.', 'Artes y Humanidades', 'Creación', 'Carmen Gil Vrolijk', 'cgil@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero Imágenes de segunda mano', 'Trabajo con imágenes encontradas y apropiadas.', 'Artes y Humanidades', 'Creación', 'Carmen Gil Vrolijk', 'cgil@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Sonido Experimental', 'Exploración y creación con sonido experimental.', 'Artes y Humanidades', 'Creación', 'Luis Ricardo Arias Vega', 'luarias@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Arte Rupestre del Orinoco (SARO)', 'Investigación sobre arte rupestre en la región del Orinoco.', 'Artes y Humanidades', 'Investigación', 'Natalia Lozada', 'n.lozada33@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero L3A', 'Laboratorio de Arte y Arqueología Andina.', 'Artes y Humanidades', 'Investigación', 'Alexander Herrera', 'alherrer@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de animación', 'Creación y desarrollo de proyectos de animación.', 'Artes y Humanidades', 'Creación', 'Juan Camilo Gonzalez Jimenez', 'j.gonzalezj@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Narrativa Sonora', 'Exploración de narrativas a través del sonido.', 'Artes y Humanidades', 'Creación', 'Charlotte De Beavoir', 'c.hebert57@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('SENDA (Semillero de experimentación en Narrativas Digitales algorítmicas)', 'Experimentación con narrativas digitales y algoritmos.', 'Artes y Humanidades', 'Creación', 'Jaime Andrés Rodríguez', 'j.rodriguezgomez@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero Qué te narras', 'Exploración de narrativas contemporáneas.', 'Artes y Humanidades', 'Creación', 'Charlotte De Beavoir', 'c.hebert57@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('AES Uniandes', 'Semillero de la Audio Engineering Society en Uniandes.', 'Artes y Humanidades', 'Investigación', 'Marcela Zorro Rodriguez', 'mp.zorro109@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Ensamble de tango', 'Grupo musical dedicado al tango.', 'Artes y Humanidades', 'Creación', 'Giovanni Parra Huertas', 'g.parrah@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Gobierno
('Liderazgo público', 'Escenario de investigación, formación y discusión sobre casos y experiencias de liderazgo público.', 'Gobierno', 'Investigación', 'Nathalie Méndez', 'n.mendez52@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Ciencias
('Grupo Uniandino de Ornitología (GUO)', 'Grupo de participación estudiantil enfocado en el reconocimiento y la apreciación de la avifauna colombiana.', 'Ciencias', 'Investigación', 'Janny Lizette González Sánchez', 'jl.gonzalezs1@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('POLAR - Semillero de Polinización en el Páramo', 'Estudio de las interacciones de polinización en el páramo de Matarredonda, documentando nuevas interacciones y polinizadores.', 'Ciencias', 'Investigación', 'Juan Camilo Dorado Suarez', 'jc.dorado@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- CIDER
('Futuros energéticos', 'Identificar, analizar y difundir experiencias de comunidades que construyen formas de vida resilientes en el contexto de la crisis planetaria.', 'CIDER', 'Investigación', 'María Cecilia Roa García', 'mc.roag@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),

-- Administración
('Élites y poder en América Latina', 'Estudio de las élites y estructuras de poder en América Latina.', 'Administración', 'Investigación y creación', 'Luis Gabriel Galán Guerrero', 'lg.galan92@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active'),
('Semillero de Finanzas', 'Investigación y análisis en temas de finanzas corporativas y mercados.', 'Administración', 'Investigación', 'Luis Guillermo Gonzalez Alvarenga', 'lg.gonzaleza1@uniandes.edu.co', '/placeholder.svg?height=400&width=600', 'active');
